### ISSUE TITLE
TypeError: argument to reversed() must be a sequence

### ISSUE THREAD

**Issue by arashmarzi** [liquidlight/tweetcam#16]
@mikestreety: 
I have cloned your repo and installed all necessary imports (TwitterAPI, requests, etc.), I have changed _config.cfg to contain my own keys and did not touch any of the other default settings from the .skel file.

When I run python bot.py, as instructed by your README, I get the following error message from my Raspberry Pi:

```
Traceback (most recent call last):
  File "bot.py", line 10, in <module>
    for tweet in reversed(mentions):
TypeError: argument to reversed() must be a sequence
```

my bot.py looks like this: 

```
#!/usr/bin/env python

# SETUP: Import global modules
import TweetStreetCam

g = TweetStreetCam.GraffCam()
mentions = g.GetMentions()

if mentions:
        for tweet in reversed(mentions):
                g.ActionTweet(tweet)

for tweet in g.GetStream():
        if 'text' in tweet:
                g.ActionTweet(tweet)

```

Im assuming this is a python problem right off the bat and might not have to do with my cloned version. The most apparent thing is that we are a TwitterResponse object back but the reversed method cannot handle it.

Do you know of a way to correct this?

**Comment by mikestreety** [comment]
@arashmarzi Hmm, this is an interesting one.

Are you able to `print(mentions)` before the `if mentions` and see what happens? Does the twitter account you're pointing to have any mentions at all? If it doesn't - that might be why - as I don't think I ever tested that edge case.

**Comment by mikestreety** [comment]
Also, can you confirm the `twitter_username` in config **does not** have the @ sign?

**Comment by arashmarzi** [comment]
I had used @ in the config file but took it out and got the same result. I added print mentions before the if clause and get the following result: 

`<bound method TwitterResponse.json of <TwitterAPI.TwitterAPI.TwitterResponse object at 0xb62da830>>`

we are getting some kind of object back; i tried using print mention.text and mention.json to see inside the object, since the TwitterAPI docs state that it has these parameters but get the following: 

AttributeError: 'function' object has no attribute 'text'
AttributeError: 'function' object has no attribute 'json'

Sadly enough, Im new to twitter, so I might be doing the 'mentioning' wrong; I'm using your repo to build a bot for snapping pictures/video of my aquariums when Im away from home. My bot's handle is @raspberryfishpi. Im assuming a mention is when i make a tweet with a given user's handle. For example I have made some test tweets from my personal account to it "@raspberryfishpi more testing is needed" and even within the bot's account made mentions of itself "@raspberryfishpi mention", but I do not see my personal accounts tweets on my bots twitter page. This is addressing your comments as to whether or not my account has any valid mentions.

**Comment by arashmarzi** [comment]
Another thing is that I did not use any single quotes around my keys or username in the config. May be negligible to mention but for some APIs i have used in the past, this can make a difference

**Comment by arashmarzi** [comment]
so I was playing around with the raw TwitterAPI to see if i can duplicate your mentions mechanism and isolate the problem, my friend and i made some mentions with my bot's handle included so it is not 100% empty.

the code

```
r = api.request('search/tweets', {'q':'@raspberryfishpi'})
for item in r:
        print(item['text'] if 'text' in item else item)
```

returns:

> @MarziArash @raspberryfishpi I've never had to use mentions, but the TwitterAPI is pretty flexible when you're using #Python
> @MarziArash @raspberryfishpi Clever. Would be really cool to automate feeding your fish while you're on vacation!
> @MarziArash @raspberryfishpi Cool! What are you working on?
> @raspberryfishpi mention
> @raspberryfishpi whats up

which is great because that is essentially looking for all tweets where my bot is mentioned, but it doesnt right my responses to my friend's messages. If i run your code: 

```
r = api.request('statuses/mentions_timeline', {'since_id': 0}).text
for item in r:
        print(item)
```

then i get:

> {"errors":[{"code":44,"message":"since_id parameter is invalid."}]}

but when i replace the since_id with my own OwnerID from my twitter app page, remove the reversed() method call, and remove the .json property at the end of self.api.request('statuses/mentions_timeline', {'since_id':  #####}) then it will work very nicely and spam my friend, but not my personal account, with messages apologizing for being late.

I guess this is a partial fix but it would be nice to know your logic for including ,json, reversed() and last_mentioned_id

**Comment by mikestreety** [comment]
Hmm interesting.

The idea is when the service starts up, it looks through your mentions since the last time it looked (which is the `last_mentioned_id`). This ID is of the _reply_ - not you.

So what it does is get the mentions, reverse them (so the oldest one is first) and loop through them one by one. Each time it does this, it makes that reply ID the last one (so if the process crashes, it knows where to start from).

I must be missing something, because this code is running fine on my Raspberry Pi...

Will investigate more tomorrow

**Comment by mikestreety** [comment]
Hi @arashmarzi 

Can you email me your config file? Just so I can check? It's probably my fault somewhere :smile: 

mikestreety@gmail.com

Thanks

**Comment by arashmarzi** [comment]
So some degree of good news:
I spent a lot of time the past two nights understanding both your code and how Twitter receives and transmits request and responses. I came to the realization that if "mentions" is a list of json mention objects, then how does the reversed() method know what json property to sort by, since each mention has a lot of properties (id, id_str, username, text...)?

Since we want to sort based on the id property then we can use this approach instead in bot.py: 

```
import TweetStreetCam

g = TweetStreetCam.GraffCam()
mentions = g.GetMentions()

# use sorted(...) with id as the key
mentions_sorted = sorted(mentions, key=lambda k:k['id'])

if mentions:
        for tweet in mentions_sorted:
                g.ActionTweet(tweet)

for tweet in g.GetStream():
        if 'text' in tweet:
                g.ActionTweet(tweet)
```

If i run this then I get I get a print out of all my mentions and sends a response tweet to that user. What do you think of this approach?

Funny side problem, but solved, was the the pi would always send out late responses "sorry i was busy can you try again". Figured out that the time zone of my pi was messed up so the time difference was 1140 or something to that effect. For the purpose my project, I do not care about time delay (plus im too lazy to fix the time zone issue :p )

I will do some code clean up and commit my full changes to my fork

**Comment by mikestreety** [comment]
Hi @arashmarzi 

Thanks for config file - didn't think it would be bogus but just wanted to check!

Your solution sounds great :smile: I'm just a little confused as to why it works for me and not for you!

I would be tempted to put the `sorted` code in the mentions method. I also realised it still has references to "Graffcam" (the old name for the project). I'll update these references once you've submitted a PR (I can assume you're going to do that? :wink:)

Understand about the delayed thing - our application is location based. E.g. you turn up somewhere, tweet and get a video of yourself in front of some cool graffiti!

Thanks for debugging - sorry I wasn't actually much help in the end!

**Comment by arashmarzi** [comment]
@mikestreety No problem, one thing I'm curious about is what version of python you are running on your pi? I was reading the docs for reversed() on the python page and came up with the following:

> reversed(seq)
> 
> ```
> Return a reverse iterator. seq must be an object which has a __reversed__() method or supports the sequence protocol (the __len__() method and the __getitem__() method with integer arguments starting at 0).
> 
> New in **version 2.4.**
> 
> Changed in **version 2.6**: Added the possibility to write a custom __reversed__() method.
> ```
> 
> Maybe our python versions are different and hence the behavior of reversed() is different? Im using Python 2.7.9.

I like your suggestion about moving the `sorted()` code to `GetMentions()` method in TweetStreetCam.py, that way all mentions processing is done in the same place ==> increase cohesion and lower coupling :P 

Yes, I will make a PR request with my fix for this issue, in case someone else runs into a similar problem. But I will then hold off on making any other cosmetic changes (like removing the delay and late messages, "GraffCam" message, more hashtag commands, logging...) so as to not affect your project's functionality.

I think it would be safe to close this issue at this point :+1:
