### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by arashmarzi** [liquidlight/tweetcam#20]
Hi @mikestreety looks like my fix for #16 created another bug in its place; it is reproduced when the last_mention_id = 0. The resulting error is: 

> {u'errors': [{u'message': u'since_id parameter is invalid.', u'code': 44}]}
> Traceback (most recent call last):
>   File "bot.py", line 7, in <module>
>     mentions = g.GetMentions()
>   File "/home/amarzi/Documents/tweetcam/TweetStreetCam.py", line 64, in GetMentions
>     mentions = sorted(mentions, key=lambda k:k['id'])
>   File "/home/amarzi/Documents/tweetcam/TweetStreetCam.py", line 64, in <lambda>
>     mentions = sorted(mentions, key=lambda k:k['id'])
> TypeError: string indices must be integers

where the first line is the contents of the mentions response from twitter.

Can you try it on your system to see if you get the same bug/result?

I have a fix for it just in case; if twitter cannot somehow handle a 0 value for since_id then we can send in a parameterless mentions_timeline request like this: `mentions = self.api.request('statuses/mentions_timeline', {}).json()` if that value is 0, otherwise we will send a parametered mentions_timeline request like before: mentions = `self.api.request('statuses/mentions_timeline', {'since_id': last_mention_id}).json()`

The revised GetMentions() method would be as follows:

```
def GetMentions(self):
                last_mention_id = self.config.get('tweets', 'last_mention_id')
                if last_mention_id == str(0):
                        mentions = self.api.request('statuses/mentions_timeline', {}).json()
                else:
                        mentions = self.api.request('statuses/mentions_timeline', {'since_id': last_m$
                mentions = sorted(mentions, key=lambda k:k['id'])
                return mentions
```

**Comment by mikestreety** [comment]
I have a plan for this, will have a look. Thanks again!

**Comment by mikestreety** [comment]
@arashmarzi sorry it got so long, think i've sorted it! Its a change in the twitter api that won't allow `0` as a `since_id` but will accept a `1`

:smile:

**Comment by arashmarzi** [comment]
silly twitter and your 1's and 0's
